version: "3"

services:
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    restart: on-failure
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    restart: on-failure
    ports:
      - "8080:8080"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: ./backend
    command: celery -A backend worker -l INFO -B
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
      - backend
volumes:
  postgres_data:
